In [70]:
import pandas as pd
import matplotlib as plt

In [71]:
attendance = pd.read_csv('attendance.csv')
games = pd.read_csv('games.csv')
standings = pd.read_csv('standings.csv')

In [72]:
arizona = attendance['team'] == 'Arizona'
year = attendance['year'] == 2000
attendance[arizona & year].fillna(0)

       team  team_name  year   total    home    away  week  weekly_attendance
0   Arizona  Cardinals  2000  893926  387475  506451     1            77434.0
1   Arizona  Cardinals  2000  893926  387475  506451     2            66009.0
2   Arizona  Cardinals  2000  893926  387475  506451     3                0.0
3   Arizona  Cardinals  2000  893926  387475  506451     4            71801.0
4   Arizona  Cardinals  2000  893926  387475  506451     5            66985.0
5   Arizona  Cardinals  2000  893926  387475  506451     6            44296.0
6   Arizona  Cardinals  2000  893926  387475  506451     7            38293.0
7   Arizona  Cardinals  2000  893926  387475  506451     8            62981.0
8   Arizona  Cardinals  2000  893926  387475  506451     9            35286.0
9   Arizona  Cardinals  2000  893926  387475  506451    10            52244.0
10  Arizona  Cardinals  2000  893926  387475  506451    11            64223.0
11  Arizona  Cardinals  2000  893926  387475  506451    12            65356.0
12  Arizona  Cardinals  2000  893926  387475  506451    13            42094.0
13  Arizona  Cardinals  2000  893926  387475  506451    14            50289.0
14  Arizona  Cardinals  2000  893926  387475  506451    15            53472.0
15  Arizona  Cardinals  2000  893926  387475  506451    16            37452.0
16  Arizona  Cardinals  2000  893926  387475  506451    17            65711.0

In [75]:
home_team_arizona = games['home_team'] == 'Arizona Cardinals'
year_2000 = games['year'] == 2000
arizona_home_2000 = games[year_2000 & home_team_arizona]
home_win = arizona_home_2000['winner'] == 'Arizona Cardinals'
arizona_home_2000[home_win].set_index(keys='week')

,year,home_team,away_team,winner,tie,day,date,time,pts_win,pts_loss,yds_win,turnovers_win,yds_loss,turnovers_loss,home_team_name,home_team_city,away_team_name,away_team_city
week,,,,,,,,,,,,,,,,,,
2,2000,Arizona Cardinals,Dallas Cowboys,Arizona Cardinals,NaN,Sun,September 10,8:35PM,32,31,322,1,330,2,Cardinals,Arizona,Cowboys,Dallas
6,2000,Arizona Cardinals,Cleveland Browns,Arizona Cardinals,NaN,Sun,October 8,4:15PM,29,21,315,2,240,0,Cardinals,Arizona,Browns,Cleveland
10,2000,Arizona Cardinals,Washington Redskins,Arizona Cardinals,NaN,Sun,November 5,4:05PM,16,15,178,2,422,3,Cardinals,Arizona,Redskins,Washington

In [80]:
standings[standings['team'] == 'Miami']

,team,team_name,year,wins,loss,points_for,points_against,points_differential,margin_of_victory,strength_of_schedule,simple_rating,offensive_ranking,defensive_ranking,playoffs,sb_winner
0,Miami,Dolphins,2000,11,5,323,226,97,6.1,1.0,7.1,0.0,7.1,Playoffs,No Superbowl
32,Miami,Dolphins,2001,11,5,344,290,54,3.4,-0.7,2.7,-0.3,3.1,Playoffs,No Superbowl
64,Miami,Dolphins,2002,9,7,378,301,77,4.8,1.2,6.1,1.7,4.4,No Playoffs,No Superbowl
95,Miami,Dolphins,2003,10,6,311,261,50,3.1,0.3,3.4,-0.7,4.1,No Playoffs,No Superbowl
129,Miami,Dolphins,2004,4,12,275,354,-79,-4.9,2.7,-2.2,-2.7,0.5,No Playoffs,No Superbowl
159,Miami,Dolphins,2005,9,7,318,317,1,0.1,-0.8,-0.8,-1.1,0.3,No Playoffs,No Superbowl
193,Miami,Dolphins,2006,6,10,260,283,-23,-1.4,2.1,0.7,-3.3,4.0,No Playoffs,No Superbowl
225,Miami,Dolphins,2007,1,15,267,437,-170,-10.6,2.3,-8.4,-4.1,-4.2,No Playoffs,No Superbowl
254,Miami,Dolphins,2008,11,5,345,317,28,1.8,-2.3,-0.5,-2.4,1.8,Playoffs,No Superbowl
288,Miami,Dolphins,2009,7,9,360,390,-30,-1.9,3.6,1.7,2.9,-1.2,No Playoffs,No Superbowl
320,Miami,Dolphins,2010,7,9,273,333,-60,-3.8,4.1,0.3,-2.8,3.1,No Playoffs,No Superbowl
352,Miami,Dolphins,2011,6,10,329,313,16,1.0,-0.1,0.9,-2.2,3.2,No Playoffs,No Superbowl
383,Miami,Dolphins,2012,7,9,288,317,-29,-1.8,-0.8,-2.6,-5.5,2.9,No Playoffs,No Superbowl
416,Miami,Dolphins,2013,8,8,317,335,-18,-1.1,0.3,-0.8,-2.9,2.1,No Playoffs,No Superbowl
448,Miami,Dolphins,2014,8,8,388,373,15,0.9,1.6,2.6,2.9,-0.4,No Playoffs,No Superbowl
481,Miami,Dolphins,2015,6,10,310,389,-79,-4.9,-1.9,-6.8,-4.7,-2.2,No Playoffs,No Superbowl
511,Miami,Dolphins,2016,10,6,363,380,-17,-1.1,-1.3,-2.4,-0.6,-1.8,Playoffs,No Superbowl
544,Miami,Dolphins,2017,6,10,281,393,-112,-7.0,0.7,-6.3,-3.9,-2.4,No Playoffs,No Superbowl
575,Miami,Dolphins,2018,7,9,319,433,-114,-7.1,-1.7,-8.8,-3.6,-5.2,No Playoffs,No Superbowl
609,Miami,Dolphins,2019,5,11,306,494,-188,-11.8,0.2,-11.6,-2.4,-9.1,No Playoffs,No Superbowl